name: Unit Testing

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Locale
        run: sudo locale-gen en_US.UTF-8 && sudo update-locale LANG=en_US.UTF-8

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Tests
        run: |
          python -m unittest discover -s tests
